//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIMOpsToolkit.Addin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BIMOpsToolkit.Addin.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Version Manager.
        /// </summary>
        public static string ButtonName_OpenVersionManager {
            get {
                return ResourceManager.GetString("ButtonName_OpenVersionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RevitVersionManager.png.
        /// </summary>
        public static string RibbonIcon_RevitVersionManager {
            get {
                return ResourceManager.GetString("RibbonIcon_RevitVersionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versioning Tools.
        /// </summary>
        public static string RibbonPanel_VersioningTools {
            get {
                return ResourceManager.GetString("RibbonPanel_VersioningTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tool allow to store Revit Model data in Database and compare mulitple versions..
        /// </summary>
        public static string RibbonTooltip_RevitVersionManager {
            get {
                return ResourceManager.GetString("RibbonTooltip_RevitVersionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIMOps Toolkit.
        /// </summary>
        public static string Tab_ToolkitName {
            get {
                return ResourceManager.GetString("Tab_ToolkitName", resourceCulture);
            }
        }
    }
}
