name: Build BIMOpsToolkit

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build Solution
        run: dotnet build RevitToolkit.sln --configuration Release --no-restore

      - name: Run NUnit Tests
        run: dotnet test RevitToolkit.Tests/RevitToolkit.Tests.csproj --configuration Release --no-build
